apiVersion: v1
kind: Pod
metadata:
  name: flask-ollama-pod
spec:
  containers:
    - name: flask-app
      image: pradhap428/pradhap428:mastodon
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Installing Ollama..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          echo "Waiting for Ollama to be ready..."
          until curl -s http://localhost:11434/; do sleep 5; done
          echo "Ollama is ready, pulling images"
          ollama pull llama3
          ollama pull paraphrase-multilingual-MiniLM-L12-v2
          echo "starting Flask app..."
          waitress-serve --host=0.0.0.0 --port=5000 src.app:app
      ports:
        - containerPort: 5000
  restartPolicy: Always
